### ISSUE TITLE
Bug report from software request

### ISSUE THREAD

**Issue by jwezel** [walles/moar#216]
Command line:

```shell
moar -no-clear-on-exit -quit-if-one-screen -wrap INPUT-FILE
```

```
Version: v1.24.1
LANG   : en_US.UTF-8
TERM   : xterm-kitty

GOOS    : linux
GOARCH  : amd64
Compiler: gc
NumCPU  : 64

panic: write /dev/stdout: file already closed [recovered]
	panic: write /dev/stdout: file already closed

goroutine 1 [running]:
main.main.func1()
	github.com/walles/moar/moar.go:793 +0x155
panic({0x639040?, 0xc000278180?})
	runtime/panic.go:770 +0x132
github.com/walles/moar/twin.(*UnixScreen).write(...)
	github.com/walles/moar/twin/screen.go:198
github.com/walles/moar/twin.(*UnixScreen).showNLines(0xc0001eff20, 0x2e, 0x60?)
	github.com/walles/moar/twin/screen.go:720 +0x385
github.com/walles/moar/twin.(*UnixScreen).ShowNLines(0xc0001eff20?, 0x8e0da0?)
	github.com/walles/moar/twin/screen.go:687 +0x15
github.com/walles/moar/m.(*Pager).ReprintAfterExit(0xc0004a0000)
	github.com/walles/moar/m/pager.go:472 +0x58
main.startPaging.func1()
	github.com/walles/moar/moar.go:851 +0x52
main.startPaging(0x0?, {0x8e4180?, 0xc0001eff20?}, 0x5?, 0x5?)
	github.com/walles/moar/moar.go:866 +0x6f
main.main()
	github.com/walles/moar/moar.go:818 +0x291
```

**Comment by walles** [comment]
Dup of #214, please subscribe / comment there!

This should now be fixed in moar v1.24.3.
