### ISSUE TITLE
moar version 1.30.0 crashed on macOS

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#259]
moar crash with follow syntax search and freeze at crash prompt

 ug 'stuck' asa.txt | ug 'loop'                                                                                                                                                                                           ✔
^[[?1049h^[[?1006;1000l^[[?25l^[]11;?^GPlease post the following report at <https://github.com/walles/moar/issues>,
or e-mail it to johan.walles@gmail.com.

Version: v1.30.0
LANG   : en_US.UTF-8
TERM   : tmux-256color
MOAR   : -colors=16M --render-unprintable=whitespace -mousemode=select
EDITOR :

GOOS    : darwin
GOARCH  : arm64
Compiler: gc
NumCPU  : 12

panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.main.func1()
        github.com/walles/moar/moar.go:598 +0x150
panic({0x1046b9560?, 0x14000134498?})
        runtime/panic.go:785 +0x124
main.startPaging.func1()
        github.com/walles/moar/moar.go:652 +0x114
panic({0x1046b9560?, 0x14000134498?})
        runtime/panic.go:785 +0x124
github.com/walles/moar/m.(*Pager).decorateLine(0x1400028a000, 0x140004481e0, {0x14000482480, 0x7, 0x7}, {0x140004481d8, 0x0, {0x104406a71, 0x5}, 0x1, ...})
        github.com/walles/moar/m/screenLines.go:362 +0xba4
github.com/walles/moar/m.(*Pager).renderLine(0x1400028a000, 0x1400035e260, {0x0}, {0x140004481d8, 0x0, {0x104406a71, 0x5}, 0x1, {0x0, 0x0, ...}})
        github.com/walles/moar/m/screenLines.go:240 +0x27c
github.com/walles/moar/m.(*scrollPositionInternal).handlePositiveDeltaScreenLines(0x1400028a020, 0x1400028a000)
        github.com/walles/moar/m/scrollPosition.go:142 +0xc0
github.com/walles/moar/m.(*scrollPositionInternal).canonicalize(0x1400028a020, 0x1400028a000)
        github.com/walles/moar/m/scrollPosition.go:255 +0x198
github.com/walles/moar/m.(*Pager).lineNumber(...)
        github.com/walles/moar/m/scrollPosition.go:277
github.com/walles/moar/m.(*Pager).renderLines(0x1400028a000)
        github.com/walles/moar/m/screenLines.go:118 +0x64
github.com/walles/moar/m.(*Pager).renderScreenLines(0x1400028a000)
        github.com/walles/moar/m/screenLines.go:77 +0x28
github.com/walles/moar/m.(*Pager).redraw(0x1400028a000, {0x0, 0x0})
        github.com/walles/moar/m/screenLines.go:42 +0x4c
github.com/walles/moar/m.(*Pager).StartPaging(0x1400028a000, {0x1046d2638, 0x1400015c0e0}, 0x1400035e0c0, 0x1400048f430)
        github.com/walles/moar/m/pager.go:350 +0x2d0
main.startPaging(0x14000112230?, {0x1046d2638?, 0x1400015c0e0?}, 0x1046cd750?, 0x14000170001?)
        github.com/walles/moar/moar.go:670 +0x54
main.main()
        github.com/walles/moar/moar.go:623 +0x234

**Comment by walles** [comment]
I've been able to reproduce this crash in a test by setting the screen width to `0`.

Do you have any idea why `moar` would think the screen width is zero on your system?

**Comment by ciscohack** [comment]
> I've been able to reproduce this crash in a test by setting the screen width to `0`.
> 
> Seems you are in `tmux`, is that right?
> 
> I wonder what would make `tmux` report zero width terminal...

Yes i am using tmux.. not sure

**Comment by walles** [comment]
Inside the `tmux` session where this crash happens:
1. Does this crash happen every time or does it sometimes work?
1. What if you just view some file in `moar` like `moar /etc/services`, does that also crash?
1. Can you try `tput cols` and post the output here?
1. Which terminal program are you using?

It's strange that you see `^[[?1049h^[[?1006;1000l^[[?25l^[]11;?^G`, which is part of `moar`'s terminal init sequence.

Kind of like something blocking `moar` from talking to the terminal.

**Comment by ciscohack** [comment]
@walles 

=> I tried 2 times and crash happened 2 times then i didn't tried.
=> tried moar /etc/services and this didn't cause crash
=> tput cols result output 172
=> i am using iterm2

**Comment by walles** [comment]
Do you have a `.ugrep` config file?

If you do, could you share it here?

**Comment by ciscohack** [comment]
> Do you have a `.ugrep` config file?
> 
> If you do, could you share it here?

[bkp.ugrep.zip](https://github.com/user-attachments/files/18280739/bkp.ugrep.zip)

Here you go

**Comment by walles** [comment]
Do you have a `~/.tmux.conf` or a `/etc/tmux` file?

If you could upload those here as well I'd like to have a look!

**Comment by ciscohack** [comment]
> Do you have a `~/.tmux.conf` or a `/etc/tmux` file?
> 
> If you could upload those here as well I'd like to have a look!

https://github.com/gpakosz/.tmux

this is what i am using just minor keybinding change nothing else ..so you can use it

**Comment by ciscohack** [comment]
@walles Any change in recent moar 1.30.1 update.. when i run ugrep "search_pattern" * then terminal is freeze and search result is very slow

**Comment by ciscohack** [comment]
> @walles Any change in recent moar 1.30.1 update.. when i run ugrep "search_pattern" * then terminal is freeze and search result is very slow..when terminal freezes i noticed moar not let to exit the moar prompt.. this is bad and it force to manual kill the terminal completely to recover it

please ignore this message .....i found the issue and it has nothing to do with moar

**Comment by walles** [comment]
Can you repro with v1.31.0? And put the crash message in this ticket?

https://github.com/walles/moar/releases/tag/v1.31.0

The crash message in this release contains more information that I hope will tell me something about what's going on.

**Comment by ciscohack** [comment]
> Can you repro with v1.31.0? And put the crash message in this ticket?
> 
> https://github.com/walles/moar/releases/tag/v1.31.0
> 
> The crash message in this release contains more information that I hope will tell me something about what's going on.

I am running moar v1.31.1 now and i am now travelling will be away from my system for longer duration

**Comment by ciscohack** [comment]
some how i got access to my system and tested 1.31.0 and issue is still there 

or e-mail it to johan.walles@gmail.com.

Version: v1.31.0
LANG   : en_US.UTF-8
TERM   : tmux-256color
MOAR   : -colors=16M --render-unprintable=whitespace -mousemode=select
EDITOR :

GOOS    : darwin
GOARCH  : arm64
Compiler: gc
NumCPU  : 12

Stdin  is a terminal: false
Stdout is a terminal: true

time="Jan  7 11:16:40.873573" level=info msg="Input stream is assumed to be uncompressed"
time="Jan  7 11:16:40.874763" level=info msg="ttyin terminal state: &{state:{termios:{Iflag:10240 Oflag:2 Cflag:19200 Lflag:67 Cc:[4 255 255 127 23 21 18 255 3 28 26 25 17 19 22 15 1 0 20 255] Ispeed:9600 Ospeed:9600}}}"
time="Jan  7 11:16:40.874777" level=info msg="ttyout terminal state: &{state:{termios:{Iflag:10240 Oflag:2 Cflag:19200 Lflag:67 Cc:[4 255 255 127 23 21 18 255 3 28 26 25 17 19 22 15 1 0 20 255] Ispeed:9600 Ospeed:9600}}}"
time="Jan  7 11:16:40.874915" level=info msg="Entering Twin main loop..."
time="Jan  7 11:16:40.875382" level=info msg="Pager starting"
time="Jan  7 11:16:40.875433" level=info msg="Entering pager main loop..."
time="Jan  7 11:16:40.875468" level=info msg="ttyin read error, twin giving up: EOF"

Panic recovery timestamp: 2025-01-07 11:16:40.875592 +0530 IST m=+0.020610126

panic: Got zero screen size: 0 x 0 [recovered]
        panic: Got zero screen size: 0 x 0 [recovered]
        panic: Got zero screen size: 0 x 0

goroutine 1 [running]:
main.main.func1()
        github.com/walles/moar/moar.go:610 +0x200
panic({0x10131ba60?, 0x14000306280?})
        runtime/panic.go:785 +0x124
main.startPaging.func1()
        github.com/walles/moar/moar.go:665 +0x114
panic({0x10131ba60?, 0x14000306280?})
        runtime/panic.go:785 +0x124
github.com/walles/moar/twin.(*UnixScreen).Size(0x1400023c000)
        github.com/walles/moar/twin/screen.go:574 +0x208
github.com/walles/moar/twin.(*UnixScreen).Clear(0x1400023c000)
        github.com/walles/moar/twin/screen.go:684 +0x80
github.com/walles/moar/m.(*Pager).redraw(0x14000312000, {0x0, 0x0})
        github.com/walles/moar/m/screenLines.go:37 +0x40
github.com/walles/moar/m.(*Pager).StartPaging(0x14000312000, {0x101366ab8, 0x1400023c000}, 0x14000492400, 0x140003f3240)
        github.com/walles/moar/m/pager.go:351 +0x2cc

**Comment by walles** [comment]
More questions:
1. Which version of ITerm2 are you using?
1. If you try another terminal (not ITerm2), do you still get this crash?
1. Does `less` work if you invoke it the same way (through `ug`)?
1. Do you know when this started happening? Months ago? Days ago? Did you change anything at that time?

---

I need to look into what these numbers mean exactly, but the terminal state is very different on your system compared to mine. Based on [the termios man page](https://www.man7.org/linux/man-pages/man3/termios.3.html) and [termios.h](https://github.com/apple/darwin-xnu/blob/main/bsd/sys/termios.h).

Yours (broken):
```
terminal state:
&{state:{termios:{Iflag:10240 Oflag:2 Cflag:19200 Lflag:67 Cc:[4 255 255 127 23 21 18 255 3 28 26 25 17 19 22 15 1 0 20 255] Ispeed:9600 Ospeed:9600}}}
```

Mine (works):
```
terminal state:
&{state:{termios:{Iflag:24580 Oflag:6 Cflag:19200 Lflag:536870983 Cc:[4 255 255 127 23 21 18 0 3 28 26 25 17 19 22 15 1 0 20 0] Ispeed:38400 Ospeed:38400}}}
```
