### ISSUE TITLE
Crash in v1.8.0

### ISSUE THREAD

**Issue by walles** [walles/moar#65]
```
Please post the following report at <https://github.com/walles/moar/issues>,
or e-mail it to johan.walles@gmail.com.

Version: v1.8.0
LANG   : sv_SE.UTF-8
TERM   : xterm-256color

GOOS    : darwin
GOARCH  : amd64
Compiler: gc
NumCPU  : 16

panic: firstInputLineOneBased 82 not found in allPossibleLines size 58 [recovered]
	panic: firstInputLineOneBased 82 not found in allPossibleLines size 58 [recovered]
	panic: firstInputLineOneBased 82 not found in allPossibleLines size 58

goroutine 1 [running]:
main.main.func1()
	/Users/walles/src/moar/moar.go:136 +0x6e
panic(0x131b420, 0xc000010010)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/panic.go:965 +0x1b9
main.startPaging.func1(0x14ac228, 0xc0000bc600, 0xc000218000)
	/Users/walles/src/moar/moar.go:274 +0x125
panic(0x131b420, 0xc000010010)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/panic.go:965 +0x1b9
github.com/walles/moar/m.(*ScreenLines).renderScreenLines(0xc0000b1be8, 0x52, 0x3a, 0xc000400060, 0x0)
	/Users/walles/src/moar/m/screenLines.go:60 +0x5c8
github.com/walles/moar/m.(*Pager)._Redraw(0xc00021a000, 0x0, 0x0)
	/Users/walles/src/moar/m/pager.go:171 +0x148
github.com/walles/moar/m.(*Pager).StartPaging(0xc00021a000, 0x14ac228, 0xc0000bc600)
	/Users/walles/src/moar/m/pager.go:663 +0x639
main.startPaging(0xc0000eb3b0, 0x0)
	/Users/walles/src/moar/moar.go:291 +0x12c
main.main()
	/Users/walles/src/moar/moar.go:247 +0x7e5
```

**Comment by walles** [comment]
Might be reproduced by using <kbd>space</kbd> for page-down in an 81 line file and a 59 high window.
